name: Build and Test

on:
  push:
    branches: ["develop", "feature"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 
      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run Pytest Tests
        run: |
          pytest
